name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - uses: BSFishy/pip-action@v1
      with:
        packages: |
          pyyaml
    - run: python setup.py build
    - run: python setup.py install
    - run: python -m unittest testing.testing
